// Bump only for a material change that needs renewed acknowledgement.
export const LEGAL_VERSION = '1.0';
export const LEGAL_STORAGE_KEY = 'novex-legal-acceptance';
export const legalDocuments = {
    terms: { title: 'Terms of Service', sections: [
        ['Initial draft — review required', 'These are initial product terms, not professional legal advice. Operator identity, jurisdiction, contact details, age requirements and moderation procedures must be reviewed and completed before public release. Nothing here excludes mandatory consumer or privacy rights.'],
        ['Using Novex', 'Novex Client is an independent launcher for Minecraft Java Edition. Use it lawfully, respect third-party terms, and keep backups of your instances and saves. You are responsible for the mods and files you choose to install.'],
        ['Accounts and ownership', 'Novex accounts provide social features through Supabase. Microsoft/Minecraft accounts authenticate Minecraft separately. You must have the rights required to use Minecraft; Microsoft sign-in alone does not establish ownership. Offline / Local Accounts do not verify ownership or authenticate to online-mode servers. Keep your account credentials secure and do not impersonate others.'],
        ['Acceptable use and social features', 'Do not use accounts, friends or chat to harass, threaten, distribute unlawful material, send spam, compromise security, or infringe others’ rights. You remain responsible for messages you send. Messages are stored on the configured Supabase service and are not end-to-end encrypted.'],
        ['Moderation and availability', 'Moderation, reporting, appeals and suspension procedures are not yet defined and require operator review. No automated moderation or guaranteed support response is promised by this draft. Features, account access and third-party services may be interrupted or changed.'],
        ['Third parties and updates', 'Microsoft, Xbox, Minecraft, Supabase, Modrinth, mod authors and loader providers have their own terms. Updates may change compatibility; review release notes and back up data. Novex checks the official GitHub release channel and offers a download link; it does not install updates automatically. No paid subscription system is included.'],
        ['Intellectual property and open source', 'Minecraft and third-party assets belong to their respective owners. Novex does not grant rights to their trademarks or game files. Dependency licenses are listed under Open Source Licenses; Novex’s own code is licensed under the MIT license in the repository LICENSE file.'],
        ['Disclaimers and limitations', 'To the extent permitted by applicable law, the application is provided without a promise of uninterrupted or error-free operation. Any limitation of liability must be reviewed for the operator’s jurisdiction and cannot remove mandatory rights or liability that cannot legally be excluded.'],
        ['Purchases and refunds', 'No Novex checkout, billing, paid products or paid services were found in this version. There are currently no Novex purchases to refund. Purchases from Minecraft or other third parties are governed by those sellers. A future paid offering needs its own reviewed terms and refund policy.'],
        ['Changes and contact', 'Material changes may require renewed acknowledgement. Contact: [operator must add a working support/legal contact before public release].']
    ] },
    privacy: { title: 'Privacy Policy', sections: [
        ['Initial draft and operator', 'This draft describes the inspected Novex source, not a verified production deployment. Data controller/operator name, contact, legal bases, hosting region, international transfer arrangements and applicable age requirements need review before public release.'],
        ['Novex account and social data', 'If you use a Novex account, the configured Supabase project receives your email address and authentication requests, profile username and optional avatar URL, user identifier, friends, friend requests, chat messages and timestamps. Passwords go to Supabase Auth through its client library. Novex uses these services for sign-in, profiles and social features. The schema enables row-level security; the deployed policies and service access have not been verified here.'],
        ['Microsoft and Minecraft', 'Microsoft sign-in occurs in your system browser. Novex does not ask for your Microsoft password. Microsoft receives the app identifier and OAuth request. The main process exchanges Microsoft credentials with Xbox Live, XSTS and Minecraft Services to check ownership and load your Minecraft UUID, username and skin. The selected Minecraft token is passed to Java to authenticate gameplay. Minecraft credentials are not sent to Supabase by Novex.'],
        ['On your device', 'Novex stores instance metadata and appearance/console preferences in Electron localStorage. Game files, worlds, mods, configuration and screenshots are in your instance folders. Launcher settings, instance-path mappings, Minecraft account display metadata and diagnostic logs are under Electron’s user data directory. The legal acknowledgement contains a document version and acceptance timestamp.'],
        ['Authentication storage', 'MSAL credentials and the Supabase session cache use Electron safeStorage encryption with the OS-backed credential facility when available. Linux basic-text storage is rejected. Without secure storage, new credentials remain in memory for the current session. Existing Supabase localStorage sessions are migrated when read and removed from localStorage after transfer. Credentials used by Supabase remain accessible to its renderer client because the existing social interface uses that client.'],
        ['Third-party network requests', 'Browsing mods or packs sends search/filter requests to Modrinth; downloads contact the file hosts in their metadata. Minecraft and loader installations contact Mojang/Microsoft, Fabric, Quilt, Forge, NeoForge and Maven hosts. Loading remote avatars, skins or project icons contacts their hosts. Network services receive information such as your IP address and request details under their own policies. Minecraft and installed mods may make additional requests independently of Novex.'],
        ['Home content and releases', 'Novex requests public Home announcements from Supabase and subscribes to content-change notifications. Admin accounts can edit Home content under server-enforced permissions. Remote banner images contact their configured HTTPS hosts; opening a slide link visits that third party in your browser. Update checks contact the public Novex GitHub release API. Downloading an installer uses GitHub in your browser. These services receive your IP address and request details.'],
        ['Diagnostics and tracking', 'The Home carousel can display clearly labeled sponsored advertisements and partner servers supplied by the operator. No analytics SDK, advertising tracker, payment processor or crash-upload service is included. Diagnostic logs record operation stages, status and limited error codes locally; Minecraft console output is filtered for the launch token. Minecraft and third-party mods can write their own logs, which Novex does not fully control. This does not establish the behavior of the Supabase deployment or third-party services.'],
        ['Security', 'Novex separates social and game credentials, restricts renderer access and checks downloaded files when hashes are provided. No security measure is absolute. Other programs running as your user, installed mods and the game process may access local data; Java authentication arguments may be visible to local process-inspection tools.'],
        ['Retention and deletion', 'Local account display data persists until removed; removing a Minecraft account removes its cached Microsoft account credentials locally but does not delete your Microsoft account or terminate a running game. Instances and settings remain until deleted. Removing local files or uninstalling does not delete Supabase server data. Server retention, backups, account-deletion requests and request handling must be defined by the operator; this version has no self-service server-account deletion flow.'],
        ['Your rights, minors and contact', 'Applicable law may provide access, correction, deletion, objection, portability or other rights. The operator must supply a working request channel and any required guardian-consent or age safeguards before public release. Contact: [operator to complete]. Material privacy changes will be published in this section.']
    ] },
    storage: { title: 'Cookie / Local Storage Policy', sections: [
        ['Desktop storage', 'Novex is an Electron desktop app. It uses Chromium localStorage for instance metadata, UI settings and legal acknowledgement; main-process JSON files for launcher settings and account display metadata; and encrypted files for authentication caches. Chromium also maintains its normal application cache/profile data.'],
        ['Cookies and other databases', 'No Novex advertising/tracking-cookie code or direct IndexedDB/sessionStorage use was found in the inspected application. This is a code finding, not a claim about third-party services. Microsoft sign-in runs in your system browser and may use Microsoft cookies under its own policies.'],
        ['Control and removal', 'Settings controls supported launcher preferences. Removing localStorage or the application user-data directory resets preferences and legal acknowledgement and can remove local account/session information. Back up instances before deleting data. Clearing local data does not delete Supabase records or browser cookies used by Microsoft.']
    ] },
    thirdParty: { title: 'Third-Party Services', sections: [
        ['Identity and social services', 'Microsoft identity platform, Xbox Live/XSTS and Minecraft Services supply game authentication and profiles. Supabase supplies the independently configured Novex account and social backend. Their terms and policies apply to their services.'],
        ['Content and downloads', 'Modrinth supplies mod, modpack and resource-pack metadata. Mojang/Microsoft supplies Minecraft metadata and downloads. Fabric, Quilt, Forge, NeoForge and Maven repositories supply loader files and libraries. Mods and packs can have their own licenses and network behavior. Novex does not vouch for every third-party file.'],
        ['Policies to review', 'Microsoft: https://privacy.microsoft.com/privacystatement · Supabase: https://supabase.com/privacy · Modrinth: https://modrinth.com/legal/privacy · Minecraft: https://www.minecraft.net/eula. Review these services’ current terms directly.']
    ] },
    disclaimer: { title: 'Minecraft / Mojang / Microsoft Disclaimer', sections: [
        ['Independent application', 'NOT AN OFFICIAL MINECRAFT PRODUCT. NOT APPROVED BY OR ASSOCIATED WITH MOJANG OR MICROSOFT.'],
        ['Ownership and distribution', 'Novex Client is independent third-party software. Minecraft, Mojang, Microsoft and associated marks belong to their owners. The Novex application package does not include Minecraft game files; it downloads required files separately from their sources. You must comply with Minecraft’s EULA and applicable usage guidelines.']
    ] }
} as const;
export type LegalDocumentId = keyof typeof legalDocuments;
